j'ai fait un build j'au eu cette erreur trouve une solution pour la corriger FETCHSOURCE BUILD Starting Step #0 - "ubuntu" Pulling image: ubuntu Using default tag: latest latest: Pulling from library/ubuntu Digest: sha256:6015f66923d7afbc53558d7ccffd325d43b4e249f41a6e93eef074c9505d2233 Status: Downloaded newer image for ubuntu\:latest docker.io/library/ubuntu\:latest Finished Step #0 - "ubuntu" Starting Step #1 - "fetch" Pulling image: gcr.io/buildpacks/firebase-app-hosting-22/builder:296af0355d8a6dfeb9dd513820312430e29df281 296af0355d8a6dfeb9dd513820312430e29df281: Pulling from buildpacks/firebase-app-hosting-22/builder 7478e0ac0f23: Pulling fs layer c3dd5f38958c: Pulling fs layer 9709bf2b448f: Pulling fs layer a74c2b09bb07: Pulling fs layer 999e8b229476: Pulling fs layer 1c9c383d63bc: Pulling fs layer 8f56d1d34e53: Pulling fs layer 182afb1fe5dc: Pulling fs layer 1a82443b3661: Pulling fs layer 2ac72a9c7e8e: Pulling fs layer 1182a6567613: Pulling fs layer a32a099c9a20: Pulling fs layer ce58163d65af: Pulling fs layer ab5065110e9b: Pulling fs layer 52f20bf313bd: Pulling fs layer 42ac8026e9a4: Pulling fs layer 565b08242743: Pulling fs layer 548eb8f86e6e: Pulling fs layer aba207a2a2a1: Pulling fs layer 2b84881ebdca: Pulling fs layer 4f4fb700ef54: Pulling fs layer 99e0f735f13b: Pulling fs layer 48c38496089a: Pulling fs layer a74c2b09bb07: Waiting 999e8b229476: Waiting 1c9c383d63bc: Waiting 8f56d1d34e53: Waiting 182afb1fe5dc: Waiting 1a82443b3661: Waiting 2ac72a9c7e8e: Waiting 1182a6567613: Waiting a32a099c9a20: Waiting ce58163d65af: Waiting ab5065110e9b: Waiting 52f20bf313bd: Waiting 42ac8026e9a4: Waiting 565b08242743: Waiting 548eb8f86e6e: Waiting aba207a2a2a1: Waiting 2b84881ebdca: Waiting 4f4fb700ef54: Waiting 99e0f735f13b: Waiting 48c38496089a: Waiting c3dd5f38958c: Verifying Checksum c3dd5f38958c: Download complete 7478e0ac0f23: Verifying Checksum 7478e0ac0f23: Download complete 999e8b229476: Verifying Checksum 999e8b229476: Download complete 1c9c383d63bc: Verifying Checksum 1c9c383d63bc: Download complete a74c2b09bb07: Verifying Checksum a74c2b09bb07: Download complete 182afb1fe5dc: Verifying Checksum 182afb1fe5dc: Download complete 8f56d1d34e53: Verifying Checksum 8f56d1d34e53: Download complete 2ac72a9c7e8e: Verifying Checksum 2ac72a9c7e8e: Download complete 1a82443b3661: Verifying Checksum 1a82443b3661: Download complete 1182a6567613: Verifying Checksum 1182a6567613: Download complete a32a099c9a20: Verifying Checksum a32a099c9a20: Download complete ce58163d65af: Verifying Checksum ce58163d65af: Download complete ab5065110e9b: Verifying Checksum ab5065110e9b: Download complete 9709bf2b448f: Verifying Checksum 9709bf2b448f: Download complete 52f20bf313bd: Verifying Checksum 52f20bf313bd: Download complete 42ac8026e9a4: Verifying Checksum 42ac8026e9a4: Download complete 548eb8f86e6e: Verifying Checksum 548eb8f86e6e: Download complete aba207a2a2a1: Verifying Checksum aba207a2a2a1: Download complete 565b08242743: Verifying Checksum 565b08242743: Download complete 2b84881ebdca: Verifying Checksum 2b84881ebdca: Download complete 4f4fb700ef54: Verifying Checksum 4f4fb700ef54: Download complete 99e0f735f13b: Verifying Checksum 99e0f735f13b: Download complete 48c38496089a: Verifying Checksum 48c38496089a: Download complete 7478e0ac0f23: Pull complete c3dd5f38958c: Pull complete 9709bf2b448f: Pull complete a74c2b09bb07: Pull complete 999e8b229476: Pull complete 1c9c383d63bc: Pull complete 8f56d1d34e53: Pull complete 182afb1fe5dc: Pull complete 1a82443b3661: Pull complete 2ac72a9c7e8e: Pull complete 1182a6567613: Pull complete a32a099c9a20: Pull complete ce58163d65af: Pull complete ab5065110e9b: Pull complete 52f20bf313bd: Pull complete 42ac8026e9a4: Pull complete 565b08242743: Pull complete 548eb8f86e6e: Pull complete aba207a2a2a1: Pull complete 2b84881ebdca: Pull complete 4f4fb700ef54: Pull complete 99e0f735f13b: Pull complete 48c38496089a: Pull complete Digest: sha256\:b9f2101b272793a52d47e2175da58c9d939b4e10399912af06789e036e246acf Status: Downloaded newer image for gcr.io/buildpacks/firebase-app-hosting-22/builder:296af0355d8a6dfeb9dd513820312430e29df281 gcr.io/buildpacks/firebase-app-hosting-22/builder:296af0355d8a6dfeb9dd513820312430e29df281 \=== Fetch Source from Signed URL === Downloading source code from signed URL... Extracting archive... Moving source code into workspace... Cleaning up temporary files and directories... Downloaded and unpacked source code from signed URL Finished Step #1 - "fetch" Starting Step #2 - "preparer" Already have image (with digest): gcr.io/buildpacks/firebase-app-hosting-22/builder:296af0355d8a6dfeb9dd513820312430e29df281 2025/05/20 13:35:13 FIREBASE\_CONFIG has no availability specified, applying the default of 'BUILD' and 'RUNTIME' 2025/05/20 13:35:13 Final app hosting schema: env:
* variable: FIREBASE\_CONFIG
  value: '{"databaseURL":"","projectId":"connecthost","storageBucket":"connecthost.firebasestorage.app"}'
  availability:

  * BUILD
  * RUNTIME
* variable: FIREBASE\_WEBAPP\_CONFIG
  value: '{"apiKey":"AIzaSyAZgZ95qTjzzXtICx9O--m9U706mrFR\_50","appId":"1:812170721595\:web\:bb01e08199c8fb31a75f1e","authDomain":"connecthost.firebaseapp.com","databaseURL":"","messagingSenderId":"812170721595","projectId":"connecthost","storageBucket":"connecthost.firebasestorage.app"}'
  availability:

  * BUILD
    2025/05/20 13:35:13 Final app hosting schema:
    env:
* variable: FIREBASE\_CONFIG
  value: '{"databaseURL":"","projectId":"connecthost","storageBucket":"connecthost.firebasestorage.app"}'
  availability:

  * BUILD
  * RUNTIME
* variable: FIREBASE\_WEBAPP\_CONFIG
  value: '{"apiKey":"AIzaSyAZgZ95qTjzzXtICx9O--m9U706mrFR\_50","appId":"1:812170721595\:web\:bb01e08199c8fb31a75f1e","authDomain":"connecthost.firebaseapp.com","databaseURL":"","messagingSenderId":"812170721595","projectId":"connecthost","storageBucket":"connecthost.firebasestorage.app"}'
  availability:

  * BUILD
    Finished Step #2 - "preparer"
    Starting Step #3 - "pack"
    Pulling image: gcr.io/k8s-skaffold/pack
    Using default tag: latest
    latest: Pulling from k8s-skaffold/pack
    396c31837116: Pulling fs layer
    9776b10d5c8c: Pulling fs layer
    52cb9ac3197f: Pulling fs layer
    9776b10d5c8c: Verifying Checksum
    9776b10d5c8c: Download complete
    396c31837116: Verifying Checksum
    396c31837116: Download complete
    52cb9ac3197f: Verifying Checksum
    52cb9ac3197f: Download complete
    396c31837116: Pull complete
    9776b10d5c8c: Pull complete
    52cb9ac3197f: Pull complete
    Digest: sha256:221c0c0d9a90f46f108bb888a1da9e99c82ff631e8b1c63b0223ea951752bd53
    Status: Downloaded newer image for gcr.io/k8s-skaffold/pack\:latest
    gcr.io/k8s-skaffold/pack\:latest
    296af0355d8a6dfeb9dd513820312430e29df281: Pulling from buildpacks/firebase-app-hosting-22/builder
    Digest: sha256\:b9f2101b272793a52d47e2175da58c9d939b4e10399912af06789e036e246acf
    Status: Image is up to date for gcr.io/buildpacks/firebase-app-hosting-22/builder:296af0355d8a6dfeb9dd513820312430e29df281
    latest: Pulling from buildpacks/firebase-app-hosting-22/run
    e1a89dea01a6: Already exists
    af059eb152dc: Already exists
    66db767fbc86: Already exists
    4972b34f89ae: Already exists
    9871e18911f2: Pulling fs layer
    9871e18911f2: Verifying Checksum
    9871e18911f2: Download complete
    9871e18911f2: Pull complete
    Digest: sha256\:b89ca4ca12099fe76da6e0f6a30430f2b21557ee8ae07b61b9963143c4862dff
    Status: Downloaded newer image for gcr.io/buildpacks/firebase-app-hosting-22/run\:latest
    \===> ANALYZING
    Image with name "us-central1-docker.pkg.dev/connecthost/firebaseapphosting-images/studio\:a-av8km4k3u7bo" not found
    \===> DETECTING
    target distro name/version labels not found, reading /etc/os-release file
    4 of 5 buildpacks participating
    google.nodejs.runtime        1.0.0
    google.nodejs.firebasenextjs 0.0.1
    google.nodejs.npm            1.1.0
    google.nodejs.firebasebundle 0.0.1
    \===> RESTORING
    \===> BUILDING
    target distro name/version labels not found, reading /etc/os-release file
    \=== Node.js - Runtime (google.nodejs.runtime\@1.0.0) ===
    2025/05/20 13:35:18 \[DEBUG] GET [https://dl.google.com/runtimes/ubuntu2204/nodejs/version.json](https://dl.google.com/runtimes/ubuntu2204/nodejs/version.json)
    Adding image label google.runtime-version: nodejs20
    2025/05/20 13:35:18 \[DEBUG] GET [https://dl.google.com/runtimes/ubuntu2204/nodejs/version.json](https://dl.google.com/runtimes/ubuntu2204/nodejs/version.json)
    \*\*\*\*\* CACHE MISS: "nodejs"
    Installing Node.js v20.19.2.
    2025/05/20 13:35:18 \[DEBUG] GET [https://dl.google.com/runtimes/ubuntu2204/nodejs/nodejs-20.19.2.tar.gz](https://dl.google.com/runtimes/ubuntu2204/nodejs/nodejs-20.19.2.tar.gz)
    \=== Node.js - Firebasenextjs (google.nodejs.firebasenextjs\@0.0.1) ===
    \*\*\*\*\* CACHE MISS: "npm\_modules"
    Installing nextjs adaptor 14.0.12
    \=== Node.js - Npm (google.nodejs.npm\@1.1.0) ===
    \*\*\*\*\* CACHE MISS: "npm\_modules"
    Installing application dependencies.

---

Running "npm ci --quiet --no-fund --no-audit (NODE\_ENV=development)"
npm warn deprecated rimraf\@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated inflight\@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @types/handlebars\@4.1.0: This is a stub types definition. handlebars provides its own type definitions, so you do not need this installed.
npm warn deprecated glob\@7.2.3: Glob versions prior to v9 are no longer supported
added 738 packages in 37s
Done "npm ci --quiet --no-fund --no-audit (NODE\_ENV=development)" (36.974215677s)
----------------------------------------------------------------------------------

Running "npm exec --prefix /layers/google.nodejs.firebasenextjs/npm\_modules apphosting-adapter-nextjs-build"
Overriding Next Config to add configs optmized for Firebase App Hosting
Successfully created next.config.ts with Firebase App Hosting overrides

> nextn\@0.1.0 build
> next build
> ▲ Next.js 15.2.3
> Creating an optimized production build ...
> ✓ Compiled successfully
> Skipping validation of types
> Skipping linting
> Collecting page data ...
> Generating static pages (0/19) ...
> Data layer initialized. Hosts and Users use Firestore. Other entities are in-memory.
> ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/login". Read more: [https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout](https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout)
> at s (/workspace/.next/server/chunks/98.js:3:24226)
> at d (/workspace/.next/server/chunks/98.js:21:70525)
> at f (/workspace/.next/server/app/login/page.js:1:5515)
> at nL (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:46773)
> at nF (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48548)
> at nq (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:67434)
> at nH (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:65009)
> at nU (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:47125)
> at nF (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48594)
> at nF (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:64360)
> Error occurred prerendering page "/login". Read more: [https://nextjs.org/docs/messages/prerender-error](https://nextjs.org/docs/messages/prerender-error)
> Export encountered an error on /login/page: /login, exiting the build.
> ⨯ Next.js build worker exited with code: 1 and signal: null
> /layers/google.nodejs.firebasenextjs/npm\_modules/node\_modules/@apphosting/common/dist/index.js:36
> reject(new Error(`Build process exited with error code ${code}.`));
> ^
> Error: Build process exited with error code 1.
> at ChildProcess.<anonymous> (/layers/google.nodejs.firebasenextjs/npm\_modules/node\_modules/@apphosting/common/dist/index.js:36:24)
> at ChildProcess.emit (node\:events:524:28)
> at ChildProcess.\_handle.onexit (node\:internal/child\_process:293:12)
> Node.js v20.19.2
> Done "npm exec --prefix /layers/google.nodejs.firebasenextjs/npm\_m..." (59.436553964s)

---

failed to build: (error ID: b087dbb6):
{"reason":"Failed Framework Build","code":"fah/failed-framework-build","userFacingMessage":"Your application failed to run the framework build command 'npm exec --prefix /layers/google.nodejs.firebasenextjs/npm\_modules apphosting-adapter-nextjs-build' successfully. Please check the raw log to address the error and confirm that your application builds locally before redeploying.","rawLog":"(error ID: d0a693a9):
Overriding Next Config to add configs optmized for Firebase App Hosting
Successfully created next.config.ts with Firebase App Hosting overrides

> nextn\@0.1.0 build
> next build
> ▲ Next.js 15.2.3
> Creating an optimized production build ...
> ✓ Compiled successfully
> Skipping validation of types
> Skipping linting
> Collecting page data ...
> Generating static pages (0/19) ...
> Data layer initialized. Hosts and Users use Firestore. Other entities are in-memory.
> ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/login". Read more: [https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout](https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout)
> at s (/workspace/.next/server/chunks/98.js:3:24226)
> at d (/workspace/.next/server/chunks/98.js:21:70525)
> at f (/workspace/.next/server/app/login/page.js:1:5515)
> at nL (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:46773)
> at nF (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48548)
> at nq (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:67434)
> at nH (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:65009)
> at nU (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:47125)
> at nF (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48594)
> at nF (/workspace/node\_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:64360)
> Error occurred prerendering page "/login". Read more: [https://nextjs.org/docs/messages/prerender-error](https://nextjs.org/docs/messages/prerender-error)
> Export encountered an error on /login/page: /login, exiting the build.
> ⨯ Next.js build worker exited with code: 1 and signal: null
> /layers/google.nodejs.firebasenextjs/npm\_modules/node\_modules/@apphosting/common/dist/index.js:36
> reject(new Error(`Build process exited with error code ${code}.`));
> ^
> Error: Build process exited with error code 1.
> at ChildProcess.<anonymous> (/layers/google.nodejs.firebasenextjs/npm\_modules/node\_modules/@apphosting/common/dist/index.js:36:24)
> at ChildProcess.emit (node\:events:524:28)
> at ChildProcess.\_handle.onexit (node\:internal/child\_process:293:12)
> Node.js v20.19.2"}
> ERROR: failed to build: exit status 1
> ERROR: failed to build: executing lifecycle: failed with status code: 51
> Finished Step #3 - "pack"
> ERROR
> ERROR: build step 3 "gcr.io/k8s-skaffold/pack" failed: step exited with non-zero status: 1