Runtime Error
Error: ./src/app/(publicClient)/reserve/[globalSiteId]/location/[locationId]/page.tsx:6:1
Export addReservation doesn't exist in target module
  4 | import React, { useEffect, useState, useCallback, Suspense } from 'react';
  5 | import { useParams, useRouter, useSearchParams } from 'next/navigation';
> 6 | import { getSiteById, getRoomOrTableById, getTags as fetchHostTags, addReservation as addReservationToData } from '@/lib/data';
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  7 | import type { Site as GlobalSiteType, RoomOrTable, Tag, Reservation } from '@/lib/types';
  8 | import { Button } from '@/components/ui/button';
  9 | import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/components/ui/card';

The export addReservation was not found in module [project]/src/lib/data.ts [app-client] (ecmascript).
Did you mean to import addReservationToData?
All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.

Show More
Call Stack
7

Show 5 ignore-listed frame(s)
<unknown>
error: ./src/app/(publicClient)/reserve/[globalSiteId]/location/[locationId]/page.tsx (6:1)
<unknown> (Error:
./src/app/(publicClient)/reserve/[globalSiteId]/location/[locationId]/page.tsx (6:1)
This error happened while generating the page. Any console logs will be displayed in the terminal window.

Was this helpful?

1